import { authenticateMaintainer, createRoomName, expect, test } from './support'

test('supports core maintainer authoring and dialog workflows', async ({ page }, testInfo) => {
  const roomName = createRoomName(testInfo)
  await authenticateMaintainer(page, roomName, testInfo)

  const insertTrigger = page.getByTitle('Insert MyST content')
  await insertTrigger.click()
  const insertDialog = page.getByRole('dialog', { name: 'Insert MyST content' })
  await expect(insertDialog).toBeVisible()
  await insertDialog.getByRole('searchbox', { name: 'Search content types' }).fill('note')
  await insertDialog.getByRole('button', { name: /^Note/ }).click()
  await expect(insertDialog).toBeHidden()
  await expect(page.locator('.cm-content')).toContainText(':::{note}')

  await page.getByTitle('Open comments').click()
  const comments = page.getByRole('complementary', { name: 'Comments' })
  await comments.getByRole('textbox', { name: 'New comment' }).fill('Browser-authored comment')
  await comments.getByRole('button', { name: 'Comment', exact: true }).click()
  await expect(comments.locator('.comment')).toContainText('Browser-authored comment')

  await page.reload()
  await expect(page.locator('.sync-status')).toHaveText('Live')
  await expect(page.locator('.cm-content')).toContainText(':::{note}')
  await page.getByTitle('Open comments').click()
  await expect(page.getByRole('complementary', { name: 'Comments' }).locator('.comment'))
    .toContainText('Browser-authored comment')
  await page.getByTitle('Close comments').click()

  await page.getByTitle('Share access').click()
  const shareDialog = page.getByRole('dialog', { name: 'Share manuscript' })
  await shareDialog.getByRole('button', { name: 'Create viewer link' }).click()
  await expect(shareDialog.getByRole('textbox', { name: 'Viewer link' })).toHaveValue(/#view=/)
  await page.keyboard.press('Escape')
  await expect(shareDialog).toBeHidden()

  await page.getByTitle('Source only').click()
  await expect(page.locator('.document-panes')).toHaveClass(/view-source/)
  await page.getByTitle('Visual editor').click()
  await expect(page.locator('.document-panes')).toHaveClass(/view-preview/)
  await page.getByTitle('Split view').click()
  await expect(page.locator('.document-panes')).toHaveClass(/view-split/)

  const helpTrigger = page.getByTitle('How DeMystify works')
  await helpTrigger.click()
  await expect(page.getByRole('dialog', { name: 'How DeMystify works' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'How DeMystify works' })).toBeHidden()
  await expect(helpTrigger).toBeFocused()

  await page.getByTitle('Manage references').click()
  await expect(page.getByRole('dialog', { name: 'Reference library' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Reference library' })).toBeHidden()

  await page.getByTitle('Publication metadata').click()
  await expect(page.getByRole('dialog', { name: 'Publication metadata' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Publication metadata' })).toBeHidden()
})

test('keeps mobile Escape ordering and focus deterministic', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const roomName = createRoomName(testInfo)
  await authenticateMaintainer(page, roomName, testInfo)

  const commentsTrigger = page.getByTitle('Open comments')
  const comments = page.getByRole('complementary', { name: 'Comments' })
  const sidebarToggle = page.locator('button[aria-controls="project-files-sidebar"]')
  const sidebar = page.getByRole('complementary', { name: 'Project files' })

  await commentsTrigger.click()
  await expect(comments).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(comments).toBeHidden()
  await expect(commentsTrigger).toBeFocused()

  await commentsTrigger.click()
  await sidebarToggle.click()
  await expect(sidebar).toHaveClass(/open/)
  await page.keyboard.press('Escape')
  await expect(sidebar).not.toHaveClass(/open/)
  await expect(comments).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(comments).toBeHidden()

  await sidebarToggle.click()
  await expect(sidebar).toHaveClass(/open/)
  const helpTrigger = page.getByTitle('How DeMystify works')
  await helpTrigger.click()
  await expect(page.getByRole('dialog', { name: 'How DeMystify works' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'How DeMystify works' })).toBeHidden()
  await expect(sidebar).toHaveClass(/open/)
  await page.keyboard.press('Escape')
  await expect(sidebar).not.toHaveClass(/open/)
})
